name: Build & Benchmark

# Performance benchmarks and cross-platform build validation
# Runs on all PRs and main branches for comprehensive testing

on:
  push:
    branches: [main, master, claude_context]
  pull_request:
    branches: [main, master, claude_context]

# Cancel in-progress runs for same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Run build benchmark
        run: pnpm benchmark

      - name: Run C++ parsing benchmark
        run: pnpm benchmark:cpp

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            build-benchmark.json
            cpp-benchmark-results.json
          retention-days: 30

      - name: Generate benchmark summary
        run: |
          echo "## Performance Benchmarks 📊" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Build Performance" >> $GITHUB_STEP_SUMMARY
          if [ -f "build-benchmark.json" ]; then
            node scripts/generate-benchmark-summary.js >> $GITHUB_STEP_SUMMARY || echo "Build benchmark completed"
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### C++ Parser Performance" >> $GITHUB_STEP_SUMMARY
          if [ -f "cpp-benchmark-results.json" ]; then
            echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
            head -10 cpp-benchmark-results.json >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          fi

  cross-platform:
    name: Cross-Platform Build (${{ matrix.os }}, Node ${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            node: '20.x'
          - os: macos-latest  
            node: '20.x'
          - os: ubuntu-latest
            node: '22.x'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build core and MCP packages
        run: |
          pnpm build:core
          pnpm build:mcp

      - name: Verify build outputs
        run: |
          echo "✅ Build completed successfully on ${{ matrix.os }} with Node ${{ matrix.node }}"
