name: Test and Benchmark

on:
  pull_request:
    branches: [master, main, claude_context]
  push:
    branches: [master, main, claude_context]

jobs:
  test-and-benchmark:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]  # Changed from 20.x to fix tree-sitter-cpp native binding issues
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build all packages
        run: pnpm build
      
      - name: Run tests with coverage (excluding flaky and extractor tests)
        run: |
          cd packages/core
          pnpm test -- --testPathPattern="cpp-parser|cpp-fixtures|smf-parser|perl-parser" --coverage
      
      - name: Run cpp-symbol-extractor tests separately  
        run: |
          cd packages/core
          pnpm test -- cpp-symbol-extractor
      
      - name: Run flaky cpp-symbol-metadata test separately
        run: |
          cd packages/core
          pnpm test -- cpp-symbol-metadata.test.ts
        continue-on-error: true
      
      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-${{ matrix.os }}-node-${{ matrix.node-version }}
          path: packages/core/coverage/
          retention-days: 30
      
      - name: Run C++ benchmark
        run: pnpm run benchmark:cpp
      
      - name: Upload C++ benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: cpp-benchmark-${{ matrix.os }}-node-${{ matrix.node-version }}
          path: cpp-benchmark-results.json
          retention-days: 30